accounts/urls.py
from django.contrib.auth.views import LoginView,LogoutView
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('signup/',views.signup,name="signup"),
    path('my_page/<int:pk>/',views.my_page,name='my_page'),
    #path('signup_done/',views.signup_done,name="signup_done"),
]

budget/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('management/',include("management.urls")),
    path('accounts/',include("accounts.urls")),
    path('',include('django.contrib.auth.urls')),
]

management/urls.py
from django.urls import path
from . import views

app_name = "management"
urlpatterns = [
    path("",views.index, name="index"),
    path("budget/add",views.budget_add,name="budget_add"),
    path("logs/",views.budget_log,name="budget_log"),
    path("budget/<uuid:id>",views.log_detail,name="log_detail"),
    path("budget/<uuid:id>/update/",views.log_update,name="log_update"),
    path("budget/<uuid:id>/delete/",views.log_delete,name="log_delete"),
    
]

management/models.py
from django.db import models
import uuid

class RecordDisplay(models.Model):
    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4,editable=False,verbose_name="ID"
    )
    income = models.IntegerField(default=0,null=True,blank=True,verbose_name="収入")
    other_income = models.IntegerField(default=0,null=True,blank=True,verbose_name="その他の収入")
    food_expenses = models.IntegerField(default=0,null=True,blank=True,verbose_name="食費")
    rent_utilities = models.IntegerField(default=0,null=True,blank=True,verbose_name="家賃＋光熱費")
    entertainment_transportation = models.IntegerField(default=0,null=True,blank=True,verbose_name="娯楽費＋交通費")
    clothing = models.IntegerField(default=0,null=True,blank=True,verbose_name="衣服")
    other_expenses = models.IntegerField(default=0,null=True,blank=True,verbose_name="その他の支出")
    page_date = models.DateField(null=True,verbose_name="日付")

    
    
    def __str__(self):
        return str(self.page_date)

management/forms.py
from django import forms
from django.forms import ModelForm
from .models import RecordDisplay
from django.utils import timezone

class IncomeForm(ModelForm):
    class Meta:
        model = RecordDisplay
        fields = ['income','other_income']

class ExpensesForm(ModelForm):
    class Meta:
        model = RecordDisplay
        fields = ['food_expenses','rent_utilities','entertainment_transportation','clothing','other_expenses']
        

class DateForm(ModelForm):
    class Meta:
        model = RecordDisplay
        fields = ['page_date']


class DateSearchForm(forms.Form):
    """履歴検索フォーム"""

    # 年の選択肢を動的に作る
    start_year = 2010  # 家計簿の登録を始めた年
    end_year = timezone.now().year + 1  # 現在の年＋１年
    years = [(year, f'{year}年') for year in reversed(range(start_year, end_year + 1))] #reversed:逆順にする
    years.insert(0, (0, ''))  # 空白の選択を追加 insert(挿入ヵ所,挿入する値){リストの最初に(0,'')を挿入}
    YEAR_CHOICES = tuple(years)

    # 月の選択肢を動的に作る
    months = [(month, f'{month}月') for month in range(1, 13)]
    months.insert(0, (0, ''))
    MONTH_CHOICES = tuple(months)
    
    # 年の選択
    year = forms.ChoiceField(
        label='年での絞り込み',
        required=False,
        choices=YEAR_CHOICES,
        widget=forms.Select(attrs={'class': 'form'})
    )

    # 月の選択
    month = forms.ChoiceField(
        label='月での絞り込み',
        required=False,
        choices=MONTH_CHOICES,
        widget=forms.Select(attrs={'class': 'form'})
    )

management/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views import View
from .models import RecordDisplay
from .forms import IncomeForm,ExpensesForm,DateForm,DateSearchForm
from django.contrib.auth.mixins import LoginRequiredMixin

class BudgetView(LoginRequiredMixin,View):
    def get(self,request):

        income_int = 0
        other_icome_int = 0
        food_expenses_int = 0
        rent_utilities_int = 0
        entertainment_transportation_int = 0
        clothing_int = 0
        other_expenses_int = 0
        
        date_all = RecordDisplay.objects.all()
        for i in date_all:
            income_int += int(i.income)
            other_icome_int += int(i.other_income)
            food_expenses_int += int(i.food_expenses)
            rent_utilities_int += int(i.rent_utilities)
            entertainment_transportation_int += int(i.entertainment_transportation)
            clothing_int += int(i.clothing)
            other_expenses_int += int(i.other_expenses)

 
        income = str(income_int)
        other_icome = str(other_icome_int)
        sum_income = str(income_int + other_icome_int)
        
        food_expenses = str(food_expenses_int)
        rent_utilities = str(rent_utilities_int)
        entertainment_transportation = str(entertainment_transportation_int)
        clothing = str(clothing_int)
        other_expenses = str(other_expenses_int)
        sum_expenses = str(food_expenses_int + rent_utilities_int + entertainment_transportation_int + clothing_int + other_expenses_int)
        
        
        return render(request,"management/index.html",
                      {'income':income,'other_income':other_icome,'sum_income':sum_income,'food_expenses':food_expenses,
                       'rent_utilities':rent_utilities,'entertainment_transportation':entertainment_transportation,
                       'clothing':clothing,'other_expenses':other_expenses,'sum_expenses':sum_expenses})


class Add(LoginRequiredMixin,View):
    def get(self,request):
        incomeform = IncomeForm()
        exoensesform = ExpensesForm()
        dateform = DateForm()
        return render(request,"management/budget_form.html",{'incomeform':incomeform,'exoensesform':exoensesform,'dateform':dateform})
    
    def post(self,request):
        incomeform = IncomeForm(request.POST)
        exoensesform = ExpensesForm(request.POST)
        dateform = DateForm(request.POST)
        if incomeform.is_valid() and exoensesform.is_valid() and dateform.is_valid():
            obj = RecordDisplay()
            obj.income = incomeform.cleaned_data['income']
            obj.other_income = incomeform.cleaned_data['other_income']
            obj.food_expenses = exoensesform.cleaned_data['food_expenses']
            obj.rent_utilities = exoensesform.cleaned_data['rent_utilities']
            obj.entertainment_transportation = exoensesform.cleaned_data['entertainment_transportation']
            obj.clothing = exoensesform.cleaned_data['clothing']
            obj.other_expenses = exoensesform.cleaned_data['other_expenses']
            obj.page_date = dateform.cleaned_data['page_date']
            obj.save()
            return redirect("management:index")
        return render(request,"management/budget_form.html",{'incomeform':incomeform,'exoensesform':exoensesform,'dateform':dateform})

class BudgetLog(LoginRequiredMixin,View):
    def get(self,request):
        search_form = DateSearchForm()
        log_list = RecordDisplay.objects.order_by("page_date")
        return render(request,"management/budget_log.html",{"log_list":log_list,'search_form':search_form})
    
    def post(self,request):
        search_form_result = DateSearchForm(request.POST)
        search_form = DateSearchForm()
        if search_form_result.is_valid():
            year = search_form_result.cleaned_data.get('year')
            month = search_form_result.cleaned_data.get('month')
            if year != '0' and month == '0':
                log_list_year = RecordDisplay.objects.filter(page_date__year=year)
                return render(request,"management/budget_log_search.html",{"log_list_year":log_list_year,'search_form':search_form})
            elif month != '0' and year == '0':
                log_list_month = RecordDisplay.objects.filter(page_date__month=month)
                return render(request,"management/budget_log_search.html",{"log_list_month":log_list_month,'search_form':search_form})
            elif year != '0' and month != '0':
                log_list_year_month = RecordDisplay.objects.filter(page_date__year=year,page_date__month=month)
                return render(request,"management/budget_log_search.html",{"log_list_year_month":log_list_year_month,'search_form':search_form})
            else:
                return redirect("management:budget_log")
                
class LogDetail(LoginRequiredMixin,View):
    def get(self,request,id):
        detail = get_object_or_404(RecordDisplay, id=id)
        return render(request,"management/log_detail.html",{"detail":detail})

class LogUpdate(LoginRequiredMixin,View):
    def get(self,request,id):
        detail = get_object_or_404(RecordDisplay, id=id)
        incomeform = IncomeForm(instance=detail)#instance=detail:既に入力されている内容も含めてフォームを作成
        exoensesform = ExpensesForm(instance=detail)
        dateform = DateForm(instance=detail)
        return render(request,"management/log_update.html",{'incomeform':incomeform,'exoensesform':exoensesform,'dateform':dateform})
    
    def post(self,request,id):
        detail = get_object_or_404(RecordDisplay, id=id)
        incomeform = IncomeForm(request.POST,instance=detail)
        exoensesform = ExpensesForm(request.POST,instance=detail)
        dateform = DateForm(request.POST,instance=detail)
        if incomeform.is_valid() and exoensesform.is_valid() and dateform.is_valid():
            incomeform.save()
            exoensesform.save()
            dateform.save()
            return redirect("management:log_detail",id=id)
        return render(request,"management/budget_form.html",{'incomeform':incomeform,'exoensesform':exoensesform,'dateform':dateform})
        
class LogDelete(LoginRequiredMixin,View):
    def get(self,request,id):
        detail = get_object_or_404(RecordDisplay,id=id)
        return render(request,'management/log_delete.html',{'detail':detail})
    
    def post(self,request,id):
        detail = get_object_or_404(RecordDisplay,id=id)
        detail.delete()
        return redirect('management:budget_log')


index = BudgetView.as_view()
budget_add = Add.as_view()
budget_log = BudgetLog.as_view()
log_detail = LogDetail.as_view()
log_update = LogUpdate.as_view()
log_delete = LogDelete.as_view()



templates/management/budget_form.html
{% extends "base/budget_base.html" %}
{% block body %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ dateform.as_p}}
    <h2>収入</h2>
    {% csrf_token %}<!--CSRF検証を自動で行う-->
    {{ incomeform.as_p }}

    <h2>支出</h2>
    {% csrf_token %}<!--CSRF検証を自動で行う-->
    {{ exoensesform.as_p }}
    <button type="submit">保存</button>
</form>
<a href="{% url 'management:index' %}">戻る</a>

{% endblock %}

templates/management/budget_log.html
{% extends "base/budget_base.html" %}
{% block body %}

<h2>履歴検索</h2>
<form class="mt-2" id="search-form" action="" method="post">
    <div>
      {% csrf_token %}
      {{ search_form.as_p }}
    </div>
    <button type="submit">検索</button>
</form>

<ul class="log-list">
    {% for log in log_list %}
        <li><a href="{% url 'management:log_detail' log.id %}">{{log.page_date}}</a></li>
    {% empty %}
        <div>収支記録がありません。</div>
    {% endfor %}
</ul>
<a href="{% url 'management:index' %}">戻る</a>
{% endblock %}

templates/management/budget_log_search.html
{% extends "base/budget_base.html" %}
{% block body %}

<form class="mt-2" id="search-form-test" action="" method="post">
    <div>
      <label class="label mr-4">年月</label>
      {% csrf_token %}
      {{ search_form.year }}
      {{ search_form.month }}
    </div>
    <button type="submit">検索</button>
</form>

<ul>
    {% if log_list_year %}
    {% for log in log_list_year %}
        <li><a href="{% url 'management:log_detail' log.id %}">{{log.page_date}}</a></li>
    {% endfor %}
    {% endif %}
    {% if log_list_month %}
    {% for log in log_list_month %}
    <li><a href="{% url 'management:log_detail' log.id %}">{{log.page_date}}</a></li>
    {% endfor %}
    {% endif %}
    {% if log_list_year_month %}
    {% for log in log_list_year_month %}
    <li><a href="{% url 'management:log_detail' log.id %}">{{log.page_date}}</a></li>
    {% endfor %}
    {% endif %}
</ul>

{% endblock %}

templates/management/index.html
{% extends "base/budget_base.html" %}
{% block body %}
<h2>収入</h2>
<table class="budget_table">
    <tr>
        <th>カテゴリー</th>
        <th>値段</th>
    </tr>
    <tr>
        <td>給料</td>
        <td>{{ income }}円</td>
    </tr>
    <tr>
        <td>その他の収入</td>
        <td>{{ other_income }}円</td>
    </tr>   
</table>
<h2>支出</h2>
<table class="budget_table">
    <tr>
        <th>カテゴリー</th>
        <th>値段</th>
    </tr>
    <tr>
        <td>食費</td>
        <td>{{ food_expenses }}円</td>
    </tr>
    <tr>
        <td>家賃＋光熱費</td>
        <td>{{ rent_utilities }}円</td>
    </tr>  
    <tr>
        <td>娯楽費＋交通費</td>
        <td>{{ entertainment_transportation }}円</td>
    </tr>
    <tr>
        <td>衣類</td>
        <td>{{ clothing }}円</td>
    </tr>
    <tr>
        <td>その他の支出</td>
        <td>{{ other_expenses }}円</td>
    </tr>
</table>
<table class="budget_table">
    <tr>
        <th>合計収入</th>
        <th>合計支出</th>
    </tr>
    <tr>
        <td>{{ sum_income }}円</td>
        <td>{{ sum_expenses }}円</td>
    </tr>

</table>
<div class="btn-container">
    <div class="btn">
        <a href="{% url 'management:budget_add' %}">収支の追加</a>
    </div>
    <div class="btn">
        <a href="{% url 'management:budget_log' %}">履歴確認</a>
    </div>
    <div class="btn">
        <a href="{% url 'accounts:my_page' user.pk %}">マイページ</a>
    </div>
</div>

<br>
<form action="{% url 'accounts:logout' %}" method="post">
    {% csrf_token %}
    <button class="logout" type="submit">ログアウト</button>
</form>

{% endblock %}

templates/management/log_delete.html
{% extends "base/budget_base.html" %}
{% block body %}

<form method="post">
    {% csrf_token %}
    <p>削除してよいですか？</p>
    <button type="submit">削除</button>
</form>
<div>{{ detail.date}}</div>
<h2>収入</h2>
<div>給料：{{ detail.income }}円</div>
<div>その他の収入：{{ detail.other_income }}円</div>
<h2>支出</h2>
<div>食費：{{ detail.food_expenses }}円</div>
<div>家賃＋光熱費：{{ detail.rent_utilities }}円</div>
<div>娯楽費＋交通費：{{ detail.entertainment_transportation }}円</div>
<div>衣類：{{ detail.clothing }}円</div>
<div>その他の支出：{{ detail.other_expenses }}円</div>

{% endblock %}

templates/management/log_detail.html
{% extends "base/budget_base.html" %}
{% block body %}

<div>{{ detail.date}}</div>
<h2>収入</h2>
<div>{{ detail.income }}円</div>
<div>{{ detail.other_income }}円</div>
<h2>支出</h2>
<div>{{ detail.food_expenses }}円</div>
<div>{{ detail.rent_utilities }}円</div>
<div>{{ detail.entertainment_transportation }}円</div>
<div>{{ detail.clothing }}円</div>
<div>{{ detail.other_expenses }}円</div>

<div><a href="{% url 'management:budget_log' %}">戻る</a></div>




{% endblock %}

templates/management/log_update.html
{% extends "base/budget_base.html" %}
{% block body %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ dateform.as_p}}
    <h2>収入</h2>
    {% csrf_token %}<!--CSRF検証を自動で行う-->
    {{ incomeform.as_p }}

    <h2>支出</h2>
    {% csrf_token %}<!--CSRF検証を自動で行う-->
    {{ exoensesform.as_p }}
    <button type="submit">更新</button>
</form>

{% endblock %}

templates/management/logout.html
{% extends "base.html" %}

<!-- コンテンツ -->
{% block content %}
<div class='container'>
  <div class="col-md-6 offset-md-3">
    <div class='card mt-3 mb-3 bg-light'>
      <!-- カードヘッダー -->
      <div class='card-header bg-primary text-light'>
        <h4>Log out</h4>
      </div>
      <!-- カードボディー -->
      <div class='card-body'>
        <p>ログアウトしました。</p>
        <p>ご利用ありがとうございました。</p>
        <hr class='mt-2 mb-2'>
        <p><a href="{% url 'management:login' %}">もう一度ログインする</a></p>
      </div>
    </div>
  </div>
</div>
{% endblock %}